### PR TITLE
add user authenticate

### PR DESCRIPTION
**Pull request by july-12**
1. add password_digest migaration
2. modify _form.html.erb
3. use sessions controller operate login and logout

### CODE REVIEW

**Comment by happypeter** [comment]
Great patch, you've learned a  lot, cngtlns!

But we have no plan to add password auth for this site. You know, we already have many users here, it will be annoying for them to add password, and it's not so necessary for now.

### Sth we do need

That is to allow people to leave comments on each event page. If you are interested, you can implement this, and I would be more than happy to merge your code then,

**Comment by july-12** [comment]
1. That't right, I forget other people have register. I think password attribute can add when someone edit them profiles
2. I interested "comments" function,  ok, I will try my best do to that.

**Comment by happypeter** [comment]
https://github.com/happypeter/offline-happycasts/issues/3
great, anything to discuss, let's post on the link above.

**Comment by happypeter** [comment]
> That't right, I forget other people have register. I think password attribute can add when someone edit them profiles

Exactly, but I don't think everybody really need the password. So let's keep this for the future.

**Pull request closed without merging**
