### PR TITLE
Add admin sendmail

### PR DESCRIPTION
**Pull request by july-12**
1. generate mailer UserMailer and controller sendmails 
2. add 'send mail' button for admin send mail all body at index.html.erb of users view

problem:  
   I try use smtp, application work, but not if I use sendmail  --development.rb
I direct user 'sendmail' command at bash it work. so I think whether have some 
need config I did't do.

### CODE REVIEW

**Comment by happypeter** [comment]
### About testing:
1. For my part, since our codebase is so so small, it does not make a lot sense to add test.
2. If you want to practice testing, that also cool, but nowadays people don't use rails' built-in test frameworks, rspec and capybara is widely used. And people don't use fixtures, they use factoryGirl.

So plz:
 Either:
     delete all your tests.
Or:
    rewrite them using capybara+rspec+factoryGirl

### Sendmail

don't worry man, I will handle this, you can use smtp for now.

**Comment by happypeter** [comment]
Tip:

When you have new commits you can still push to this `add_admin_sendmail` branch, then this pull request will be updated, and I will notice, so that you don't need to send another PR.

**Comment by happypeter** [comment]
http://happycasts.net/episodes/57

**Comment by july-12** [comment]
ok,  I gad know tip 
for practice testing, I want to delay it, because I want to add style for project! so I delete all  tests

**Comment by happypeter** [comment]
@july-12 so plz delete all the test files, and also OK to delete the whole test/ dir，since we will never use it.
then make a commit on add_admin_sendmail branch and push to github。

After you do that, this PR will be changed, so that I can merge it into master.

**Comment by july-12** [comment]
@happypeter  I have delete whole test dir,  what's next assignment?

**Comment by happypeter** [comment]
Next Task will be: https://github.com/happypeter/offline-happycasts/issues/3#issuecomment-16623281

**Pull request closed without merging**
